### ISSUE TITLE
Update shebang

### ISSUE THREAD

**Issue by Zettt** [hzulla/tolino-python#14]
Good morning.

I'm running this on macOS/OS X. I think the shebang at the beginning is not correct, but I might be mistaken. As far as I'm aware, it shouldn't directly link to `python3. Instead it should be something like:

```
#!/usr/bin/env python3
```

I'm not sure if this works though. I'm not super advanced with Python. I'm using Homebrew on OS X and it installs Python 3 into `/usr/local/bin/python3` by default. 

Changing the shebang to `/usr/local/bin/python3` gives me an error, but at least it doesn't ask for Python 3 anymore.

**Comment by zauguin** [comment]
The /usr/bin/env shebang should always work, but for you /usr/local/bin/python3 is supposed to work too.
Can you post the error message?
