### ISSUE TITLE
after updating the system i get ...

### ISSUE THREAD

**Issue by Barnestos** [hzulla/tolino-python#16]
Hello,
First, i want to say that your program is the perfect completion to the tolino.
But, since today  get the following messages:

Traceback (most recent call last):
  File "/home/bernhard/tolino/tolinocloud.py", line 251, in login
    self.access_token = base64.b64decode(b64).decode('utf-8')
  File "/usr/lib/python3.5/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bernhard/tolino/tolinoclient.py", line 161, in <module>
    args.func(args)
  File "/home/bernhard/tolino/tolinoclient.py", line 47, in devices
    c.login(args.user, args.password)
  File "/home/bernhard/tolino/tolinocloud.py", line 253, in login
    raise TolinoException('oauth access token request failed.')
tolinocloud.TolinoException: oauth access token request failed.

thank you,
Bernhard

**Comment by Barnestos** [comment]
it has maybe something to do with thalia.de.Because when i change to thalia.at it still works...

            # Thalia.at
            'client_id'        : 'webshop01',
            'scope'            : 'SCOPE_BOSH SCOPE_BUCHDE',
            'signup_url'       : 'https://www.thalia.at/shop/home/kunde/neu/',
            'profile_url'      : 'https://www.thalia.at/shop/home/kunde/',
            'login_url'        : 'https://www.thalia.at/shop/home/login/dologin/',
            'login_form'       : {
                'username' : 'username',
                'password' : 'password',
                'jumpId'   : 'jumpId',
                'token'    : '_token',
                'extra'    : {'cmd3' : ''}
             },
            'login_cookie'     : 'KUNDE',
            'tat_url'          : 'https://www.thalia.at/shop/home/ebook/anzeigen/',
            'logout_url'       : 'https://www.thalia.at/shop/home/login/logout/',
            'reader_url'       : 'https://html5reader.thalia.at/library/library.html#!/library',
            'register_url'     : 'https://bosh.pageplace.de/bosh/rest/registerhw',
            'devices_url'      : 'https://bosh.pageplace.de/bosh/rest/handshake/devices/list',
            'unregister_url'   : 'https://bosh.pageplace.de/bosh/rest/handshake/devices/delete',
            'upload_url'       : 'https://bosh.pageplace.de/bosh/rest/upload',
            'delete_url'       : 'https://bosh.pageplace.de/bosh/rest/deletecontent',
            'inventory_url'    : 'https://bosh.pageplace.de/bosh/rest/inventory/delta',
            'downloadinfo_url' : 'https://bosh.pageplace.de/bosh/rest//cloud/downloadinfo/{}/{}/type/external-download'

mfg,
bernhard

**Comment by Barnestos** [comment]
there was a '%3D%3D' at the end of the token.
I replaced  it with '=': 
>>>tolinocloud.py
               ...
                b64 = re.search(r'\?tat=(.*?)\"', r.text).group(1) 
                b64 = b64.replace('%3D', '=')   <<<<<<<<<<<<< that will do the trick...
                self.access_token = base64.b64decode(b64).decode('utf-8')
                ...
>>>
now it's working normal.

mfg,
Bernhard

**Comment by theopenbit** [comment]
this fix is working for me too!
Are you able to make a merge request for it?

**Comment by Barnestos** [comment]
I'm a newbie on github...

**Comment by theopenbit** [comment]
Hi Barnestos, I've integrated your fix in my fork and made a merge request for it. 
Thank you for bugfixing!
