### ISSUE TITLE
Can you support buecher.de ?

### ISSUE THREAD

**Issue by aquisx** [hzulla/tolino-python#20]
It would be nice if you add buecher.de to your Script or how do i find out what is the scope and what is the client id to add it self.

**Comment by hzulla** [comment]
@aquisx please try the changes that @A7r-S6s just added.

**Comment by A7r-S6s** [comment]
Regarding @aquisx second part of the question: I used Firefox' developer tools and the network analysis tab while accessing the Tolino webreader.
Needed some fiddling around, guessing and trial & error until I identified the correct URLs, parameters and tokens for buecher.de to work.
It all had to be added to the corresponding partner settings element in [tolinocloud.py](https://github.com/hzulla/tolino-python/blob/master/tolinocloud.py)

**Comment by hzulla** [comment]
PSA: Hello there. I have stopped maintaining this library, as I do not own a Tolino anymore. If this library is still useful to you, I'd want to hand it over to a new maintainer. Thank you. As this issue is outdated, I'm closing it.
