### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by tuxbox78** [hzulla/tolino-python#24]
Hi,
since yesterday i get the following errors when trying to access my (thalia.de) tolino cloud account
with tolino-python:

Traceback (most recent call last):
  File "./tolinoclient.py", line 161, in <module>
    args.func(args)
  File "./tolinoclient.py", line 19, in inventory
    c.login(args.user, args.password)
  File "/home/fseidel/myTolino/tolinocloud.py", line 230, in login
    jumpId=re.search(r'\?jumpId=(.*?)\"', r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

What could i do?

Thx,Frank

**Comment by Barnestos** [comment]
i have the same error...

anyone has an answer? - please!
Bernhard

**Comment by hzulla** [comment]
Forgive me, but I do not actively maintain this project anymore. The makers of Tolino do not support 3rd party clients and all requests for a protocol description were denied.

**Comment by theopenbit** [comment]
I've take a short look at it. I think they changed some URLs and it  looks like there new parameters in the requests. When I've a bit lazy time I will take a deeper lock in it

**Comment by theopenbit** [comment]
It seems they added a csrf check to the login form. Up to now I can't handle it correctly neither using curl nor patching tolinocloud.py :-(

**Comment by theopenbit** [comment]
I fixed the problem by switching to oauth2 for thalia.de and I need to fix some requests to bosh.pageplace.de/bosh. I think theses changed are important for other tolino patners, too. Is there anyone using this project with other partners than thalia.de?

**Comment by Barnestos** [comment]
Thanks a lot!
I am using thalia.at

**Comment by theopenbit** [comment]
@Barnestos  thalia.at great! I think we need to change a few links for them, too. Until the merge request is integrated you need to test it using the forked repo https://github.com/theopenbit/tolino-python. Please test the connection with that version. If it is not working, take a look at the thalia.at configuration in tolinocloud.py and modifiy them corresponding to the configuration of thalia.de. Maybe this will fix it for you

**Comment by shoeper** [comment]
I can confirm that the change in #25 works with at least my thalia.de account.

@theopenbit thank you very much for fixing it! and thanks @hzulla for developing this :)
