### ISSUE TITLE
tolinocloud.TolinoException: register <HARDWARE_ID> failed.

### ISSUE THREAD

**Issue by mklemm2** [hzulla/tolino-python#26]
Hi,

I wanted to give it a try but it seems like it's currently not working for Hugendubel:

```
./tolinoclient.py --partner 13 --user <LOGIN> --password <PASSWORD> inventory
Traceback (most recent call last):
  File "./tolinoclient.py", line 161, in <module>
    args.func(args)
  File "./tolinoclient.py", line 20, in inventory
    c.register()
  File "/<PATH>/tolino-python/tolinocloud.py", line 335, in register
    raise TolinoException('register {} failed.'.format(TolinoCloud.hardware_id))
tolinocloud.TolinoException: register <HARDWARE_ID> failed.
```

**Comment by theopenbit** [comment]
hmm, the ```TolinoCloud.hardware_id``` is a pseudo id. Maybe Hugendubel don't like it. Inspect the network traffic if you are login with your browser. There must be a header with a field hardware_id in the request to https://bosh.pageplace.de/bosh/rest/registerhw
Put this id in line 326 of the file tolinocloud.py instead of ```TolinoCloud.hardware_id``` and give it a try

**Comment by colorchestra** [comment]
I have the same problem. Unfortunately I couldn't get my browser to make a request to https://bosh.pageplace.de/bosh/rest/registerhw, but (if that works as well) a request to https://bosh.pageplace.de/bosh/rest/upload had a `hardware_id` header. I changed `_hardware_id` to always return that ID, but to no avail, the error stays the same.

**Comment by theopenbit** [comment]
what does the hardware_id in the traffic if using the browser looks like?

**Comment by hzulla** [comment]
PSA: Hello there. I have stopped maintaining this library, as I do not own a Tolino anymore. If this library is still useful to you, I'd want to hand it over to a new maintainer. Thank you. As this issue is outdated, I'm closing it.
