### ISSUE TITLE
Add a way to download all books

### ISSUE THREAD

**Issue by nandolawson** [hzulla/tolino-python#31]
It would be great to download all books at once so I would be able to begin syncing my ebooks with my PC. :)

**Comment by hzulla** [comment]
PSA: Hello there. I have stopped maintaining this library, as I do not own a Tolino anymore. If this library is still useful to you, I'd want to hand it over to a new maintainer. Thank you. As this issue is outdated, I'm closing it.

**Comment by nandolawson** [comment]
The project is pretty outdated, I'd continue to maintain it and add some new features if you like.
