### ISSUE TITLE
Can you add support to orellfuessli.ch?

### ISSUE THREAD

**Issue by t0000** [hzulla/tolino-python#34]
Hello
would it be possible to add orellfuessli.ch? That would be great for all swiss users :)

Regards

**Comment by hzulla** [comment]
There is no active development on this code, as I do not own a Tolino anymore and the device developers never responded to any request about the API.

I will gladly accept a patch to add support, though.

**Comment by hzulla** [comment]
PSA: Hello there. I have stopped maintaining this library, as I do not own a Tolino anymore. If this library is still useful to you, I'd want to hand it over to a new maintainer. Thank you. As this issue is outdated, I'm closing it.
