### ISSUE TITLE
Hugendubel.de not working anymore

### ISSUE THREAD

**Issue by uhinze** [hzulla/tolino-python#36]
Saw that there's no active development anymore, but I wanted to try out Hugendubel anyway. Turns out it's broken in a lot of places. Not only partner endpoints but the whole flow seems to have changed (e.g. there's no call to `auth_url` anymore, and `token` endpoint returns `accessToken` and `refreshToken` instead of `access_token`, `refresh_token` and `expires_in`). That's how far I got but it still doesn't work with some adaptations.
Sorry to see this breaking, thought it was a great idea! But yeah if Tolino doesn't want to support an independent ecosystem I guess there's not much you can do.

**Comment by hzulla** [comment]
PSA: Hello there. I have stopped maintaining this library, as I do not own a Tolino anymore. If this library is still useful to you, I'd want to hand it over to a new maintainer. Thank you. As this issue is outdated, I'm closing it.

**Comment by uhinze** [comment]
Appreciate the note.
