### ISSUE TITLE
Support for orellfuessli

### ISSUE THREAD

**Issue by gottschali** [hzulla/tolino-python#37]
[orellfuessli.ch](https://www.orellfuessli.ch) is the second Tolino partner in Switzerland next to weltbild.
I would like to help but I know nothing about REST interfaces yet.
I contacted their supported and I am waiting for a response.

**Comment by h1f0x** [comment]
I built it, pull request is currently open for merge :-)

**Comment by Aliuakbar** [comment]
That's so cool to hear!
Would you mind to explain me briefly how you did it?
Btw you can reference the issue in your pull request.

**Comment by h1f0x** [comment]
Thank you! I forgot to link it :-) Well briefly explained: I intercepted the traffic from of the website and checked for the corresponding urls. Lucky for me was, that the urls are almost the same as thalia.de. What I sadly did not get to work that night, was to generate the collections like its possible within the tolino webreader. Someday I may check again and see if I find a way.
