### ISSUE TITLE
Is using this okay with the Tolino Cloud/Thalia ToS?

### ISSUE THREAD

**Issue by toXel** [hzulla/tolino-python#41]
I don't wanna lose my Tolino account. Are there any known cases of bans?

**Comment by hzulla** [comment]
You should ask Tolino. I did my best to contact them and ask them for API access, but never got any reply. Also, my Tolino account was never banned.

(Note that I do not maintain this code anymore.)

**Comment by toXel** [comment]
Ok thanks for the answer. Yea maybe I should write them just to be on the safe side.

I'm not planning to use this code directly. It's more of a template for me as I'm planning to implement a Tolino library in Go. So thanks for the work you already did here!
