### ISSUE TITLE
Could you port this to .net to use it in custom applications?

### ISSUE THREAD

**Issue by furesoft** [hzulla/tolino-python#43]

**Comment by hzulla** [comment]
This library is open source. You're free to port to .net, but of you want me to do it for you, we need to discuss hourly rates.

**Comment by hzulla** [comment]
PSA: Hello there. I have stopped maintaining this library, as I do not own a Tolino anymore. If this library is still useful to you, I'd want to hand it over to a new maintainer. Thank you. As this issue is outdated, I'm closing it.
