### ISSUE TITLE
Add ability to upload covers

### ISSUE THREAD

**Issue by darkphoenix** [hzulla/tolino-python#44]
I didn't want to open a PR for this as I don't have anything finished, but for my own project (using the library from this to upload my Calibre library) I implemented uploading covers, and it does appear to work (though some of the cover images in my Calibre are clearly too big).  I didn't implement a CLI command to actually use it, but fwiw you might be interested in the add_cover function anyway.  The fork is darkphoenix/tolino-calibre-python - I created a separate commit for this one change, should you be interested in merging it.

**Comment by darkphoenix** [comment]
I've at this point improved a few things, added various features (basic collection management, covers, metadata), as well as pulled together Osiander and orellfuessli.ch partner configurations based on some of the other forks of this repository.  My focus is of course on my own sync tool, but I've taken care to also integrate the new features into tolinoclient.py.  You're apparently not interested in maintaining this repo further, so would you consider pointing people to my fork instead?

**Comment by hzulla** [comment]
PSA: Hello there. I have stopped maintaining this library, as I do not own a Tolino anymore. If this library is still useful to you, I'd want to hand it over to a new maintainer. Thank you. As this issue is outdated, I'm closing it.
