### ISSUE TITLE
login failed for hugendubel

### ISSUE THREAD

**Issue by cultcom** [hzulla/tolino-python#5]
Hi,

it appears as if the hugendubel URLs changed. I always get a "login failed" with the current master branch.

--debug shows a 404 error:
```
DEBUG:root:text: <html><head><title>Apache Tomcat/6.0.36 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /go/my_dry/my_login/lfa/login/receiver_object/my_login/</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/go/my_dry/my_login/lfa/login/receiver_object/my_login/</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/6.0.36</h3></body></html>
DEBUG:root:-------------------------------------------------------
```

**Comment by Gomez** [comment]
You could try with the newest commit. Works here again with thalia.

**Comment by cultcom** [comment]
nope, still not working. I guess the URLs changed maybe?

> $ ./tolinoclient.py --debug inventory
> INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.hugendubel.de
> DEBUG:urllib3.connectionpool:Setting read timeout to None
> DEBUG:urllib3.connectionpool:"POST /go/my_dry/my_login/lfa/login/receiver_object/my_login/ HTTP/1.1" 404 20
> DEBUG:root:-------------------- HTTP response --------------------
> DEBUG:root:status code: 404
> DEBUG:root:cookies: <<class 'requests.cookies.RequestsCookieJar'>[Cookie(version=0, name='JSESSIONID', value='ED06109F9D8BABE2492B495BE6457DE0.www04', port=None, port_specified=False, domain='www.hugendubel.de', domain_specified=False, domain_initial_dot=False, path='/', path_specified=True, secure=True, expires=None, discard=True, comment=None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False)]>
> DEBUG:root:headers: CaseInsensitiveDict({'vary': 'Accept-Encoding', 'set-cookie': 'JSESSIONID=ED06109F9D8BABE2492B495BE6457DE0.www04; Path=/; Secure; HttpOnly', 'connection': 'Keep-Alive', 'date': 'Tue, 22 Sep 2015 14:46:54 GMT', 'content-type': 'text/plain; charset=UTF-8', 'content-length': '20', 'content-encoding': 'gzip', 'server': 'Apache', 'access-control-allow-origin': '*'})
> DEBUG:root:text:
> DEBUG:root:-------------------------------------------------------
> Traceback (most recent call last):
>   File "./tolinoclient.py", line 158, in <module>
>     args.func(args)
>   File "./tolinoclient.py", line 18, in inventory
>     c.login(args.user, args.password)
>   File "/home/wigge/workdir/tolino-python/tolinocloud.py", line 227, in login
>     format(self.partner_name[self.partner_id]))
> tolinocloud.TolinoException: login to Hugendubel.de failed.
